apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${REDIS_SERVICE_PREFIX}-redis
    name: ${REDIS_SERVICE_PREFIX}-redis
  spec:
    replicas: 5
    selector:
      app: ${REDIS_SERVICE_PREFIX}-redis
    template:
      metadata:
        labels:
          app: ${REDIS_SERVICE_PREFIX}-redis
      spec:
        containers:
        - env:
            - name: REDIS_DATA_MAX_AGE
              value: ${REDIS_DATA_MAX_AGE}
            - name: REDIS_SENTINEL_SERVICE_HOST
              value: ${REDIS_SERVICE_PREFIX}-redis-sentinel
            - name: REDIS_SENTINEL_SERVICE_PORT
              value: ${REDIS_SENTINEL_SERVICE_PORT}
            - name: REDIS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ${REDIS_IMAGE}
          imagePullPolicy: Always
          name: ${REDIS_SERVICE_PREFIX}-redis
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: data
          ports:
            - containerPort: 6379
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: ${REDIS_PV}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${REDIS_SERVICE_PREFIX}-redis
        from:
          kind: ImageStreamTag
          name: ${REDIS_IMAGE}
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${REDIS_SERVICE_PREFIX}-redis
    name: ${REDIS_SERVICE_PREFIX}-redis
  spec:
    ports:
      - port: 6379
        targetPort: 6379
    selector:
      app: ${REDIS_SERVICE_PREFIX}-redis

parameters:
- name: REDIS_SERVICE_PREFIX                                                                            
  description: Name of the redis service. It is used as the prefix for all components.                  
  required: true                                                                                        
- name: REDIS_IMAGE                                                                            
  description: Location and name of the Redis Sentinel image.                                           
  required: true                                                                                        
- name: REDIS_PV                                                                            
  description: Name of the Redis PV to bind.                                           
  required: true                                                                                        
- name: REDIS_DATA_MAX_AGE                                                                            
  description: Maximal age of slave data directories in days.
  required: true
  value: "4"
- name: REDIS_SENTINEL_SERVICE_PORT
  description: Port of the redis sentinel service
  required: true
  value: "26379"
